name: med_hackton
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter
  equatable: ^2.0.5
  flutter_bloc: ^8.1.6
  numberpicker: ^2.1.2
  flutter_floating_bottom_bar: ^1.2.1+1
  syncfusion_flutter_charts: ^27.2.2
  flutter_speed_dial: ^7.0.0
  textfield_datepicker: ^0.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
